import '../sass/stylesheets/main.scss';
import './modulos/1-fundamentos/variables/ejercicio.js';
import './modulos/1-fundamentos/estructura-control/ejercicios.js';
import './modulos/1-fundamentos/funciones/ejercicios.js';
import './modulos/2-array-avanzados/metodos/ejercicios.js';
import './modulos/2-array-avanzados/metodos/prueba_tecnica.js';
import './modulos/2-array-avanzados/matrices/ejercicio.js';
import './modulos/2-array-avanzados/optimizacion/ejercicio.js';
import './modulos/asincronia-apis/introduccion/ejercicios.js';